# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, release ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # checkout to the commit that has been pushed
      - uses: actions/checkout@v2
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0   # Fetch all history for .GitInfo and .Lastmod
      
      - name: Hugo setup
        # You may pin to the exact commit or the version.
        # uses: peaceiris/actions-hugo@2e89aa66d0093e4cd14751b3028fc1a179452c2e
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          # The Hugo version to download (if necessary) and use. Example: 0.58.2
          hugo-version: '0.93.0' # optional, default is latest
          # Download (if necessary) and use Hugo extended version. Example: true
          extended: true # optional, default is false
      
      # build website
      - name: Build
        run: hugo -D
      
      # push the generated content into the `main` branch.
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          personal_token: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
          external_repository: xwi88/xwi88.github.io
          publish_branch: main
          publish_dir: ./public
          full_commit_message: ${{ github.event.head_commit.message }}
      
      - name: Deploy_Gitee
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages # default
          full_commit_message: ${{ github.event.head_commit.message }}

      - name: Rsync Deployments
        uses: burnett01/rsync-deployments@5.2
        with:
          # The switches
          switches: -avzh
          # The remote shell argument
          # rsh: # optional, default is
          path: ./public/*  # The local path
          remote_path: /home/app/public/ # optional, default is
          remote_host: xwi88.com
          remote_port: 65432 # optional, default is 22
          remote_user: app
          remote_key: ${{ secrets.SITE_RSA_PRIVATE_KEY }} # shall not use root
          # The remote key passphrase
          # remote_key_pass: # optional, default is

  sync:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      with:
        source-repo: "git@github.com:xwi88/xwi88.github.io.source.git"
        destination-repo: "git@gitee.com:xwi88/xwi88.git"

  gitee-pages:
    needs: sync
    runs-on: ubuntu-latest
    steps:
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: xwi88
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: xwi88/xwi88
          branch: gh-pages
